# Generated by Django 4.2.1 on 2023-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(blank=True)),
                ('reqmail', models.TextField(blank=True)),
                ('reqinfo', models.TextField(blank=True)),
                ('reqmail_list', models.TextField(blank=True)),
                ('reqlist', models.TextField(blank=True)),
            ],
        ),
    ]
