# Generated by Django 4.2.1 on 2023-05-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqmail', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='reqinfo',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='reqlist',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='reqmail',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='reqmail_list',
        ),
        migrations.AddField(
            model_name='requests',
            name='req_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='requests.request_mails'),
        ),
    ]
