# Generated by Django 4.2.1 on 2023-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_mails_remove_requests_reqinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='req_mail',
        ),
        migrations.AddField(
            model_name='requests',
            name='reqmail',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='request_mails',
        ),
    ]
