# Generated by Django 4.2.1 on 2023-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_reqmails_remove_requests_reqmail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
        migrations.RenameModel(
            old_name='Reqmails',
            new_name='RequestMessage',
        ),
    ]
