# Generated by Django 4.2.1 on 2023-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_rename_requests_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestMessage',
        ),
        migrations.AddField(
            model_name='request',
            name='reqmail',
            field=models.TextField(blank=True, verbose_name='Содержание заявки'),
        ),
    ]
