# Generated by Django 4.2.1 on 2023-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_delete_requestmessage_request_reqmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqmail', models.TextField(blank=True, verbose_name='Содержание заявки')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='reqmail',
        ),
    ]
