# Generated by Django 4.2.1 on 2023-05-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_request_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='userid',
        ),
    ]
