# Generated by Django 4.2.1 on 2023-05-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_alter_request_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='userid',
            new_name='user',
        ),
    ]
