# Generated by Django 4.2.1 on 2023-05-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='requests.request'),
        ),
    ]
