# Generated by Django 4.2.1 on 2023-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_requestmessage_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmessage',
            name='request',
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='request_id',
            field=models.TextField(blank=True, verbose_name='id заявки'),
        ),
    ]
