# Generated by Django 4.2.1 on 2023-05-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_remove_requestmessage_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmessage',
            name='request_id',
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='requests.request'),
        ),
    ]
